version: "3.6"

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.84.0
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./collector.yaml:/etc/otelcol/config.yaml
    environment:
      - NEW_RELIC_OTLP_ENDPOINT
      - NEW_RELIC_API_KEY
      - CLUSTER_BOOTSTRAP_SERVER
      - CLUSTER_API_KEY
      - CLUSTER_API_SECRET
      - CONFLUENT_API_ID
      - CONFLUENT_API_SECRET
      - CLUSTER_ID
    ports:
      - "4317:4317"
      - "4318:4318"


